# Generated by Django 2.2.20 on 2021-11-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('name', models.CharField(max_length=40)),
                ('phone', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('message', models.TextField()),
            ],
        ),
    ]
